---
title: "P8106_Mtp"
author: "Ekta Chaudhary"
date: "26/03/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
```


```{r}
library(tidyverse)
library(readxl)
library(caret)
library(ModelMetrics)
library(glmnet)
library(gam)
library(mgcv)
library(splines)
library(pdp)
library(earth)
library(dplyr)
library(naniar)
library(bnstruct)
library(corrplot)
library(logisticPCA)
```
Reading the Datasets 

```{r}
Diagnosis = 
read_csv('./data/Diagnosis.csv')
Prognosis = 
  read_csv('./data/Prognosis.csv')
Breast_Cancer = 
  read_csv(file = './data/Breast_Cancer.csv' ,col_names = c('id_number','Clump_thickness','Uniformity_of_Cell_Size','Uniformity','Marginal_Adhesion','Epithelial_Cell_Size','Bare_Nuclei','Bland_Chromatin','Normal_Nucleoli','Mitoses','Class_cancer')) 
  
```


```{r}
Breast_Cancer = Breast_Cancer %>% replace_with_na_all(condition = ~.x == '?')

```

```{r}
Breast_Cancer <- knn.impute(as.matrix(Breast_Cancer), k = 10, cat.var = 2:ncol(Breast_Cancer) - 2,
  to.impute = 1:nrow(Breast_Cancer), using = 1:nrow(Breast_Cancer))
```

```{r}
Breast_Cancer <- data.frame(Breast_Cancer)
```

```{r}

Breast_Cancer$Class_cancer = ifelse(Breast_Cancer$Class_cancer == 4, 1,0)
Breast_Cancer = Breast_Cancer[,2:11]
```

```{r}
x = model.matrix(Class_cancer~., Breast_Cancer) [,-1]

corrplot(cor(x))
```


```{r}

lpca = cv.lpca(Breast_Cancer[,1:9], ks = 2, ms = 1:10)
```


```{r}
plot(lpca)
```

```{r}
cancer.pca <- prcomp(Breast_Cancer[,1:9],center = TRUE , scale. = TRUE)
```
```{r}
summary(cancer.pca)
```
```{r}
cancer.pca[2]
```






